### ISSUE TITLE
Should the latest stable release of wordsmith 3.3.0 have a requirement of > craft 3.5 which is unstable?

### ISSUE THREAD

**Issue by joepagan** [TopShelfCraft/Wordsmith#36]
I know you've done it to prep, but feels like this should not yet be a requirement when there is not yet a stable release of that package?

Thanks for your work.

**Comment by michaelrog** [comment]
Composer will satisfy dependency requirements with the latest possible packages based on your project's [stability setting](https://getcomposer.org/doc/04-schema.md#minimum-stability). i.e. Unless you specifically allow beta/RC versions of dependencies in your `composer.json`, you won't get Craft 3.5 (or Wordsmith 3.3) until P&T tags a "stable" release.

Craft 3.5 requires a different version of Stringy than previous releases, which is why Wordsmith 3.3 requires Craft 3.5 — Installing Wordsmith 3.3 on a previous version of Craft would cause a dependency conflict and break the install.

**Comment by joepagan** [comment]
Forgive me if I haven't understood this right though composer takes "stable" by default?

`composer create-project craftcms/craft`

then 

`composer require topshelfcraft/wordsmith`

returns:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for topshelfcraft/wordsmith ^3.3 -> satisfiable by topshelfcraft/wordsmith[3.3.0].
    - topshelfcraft/wordsmith 3.3.0 requires craftcms/cms ^3.5 -> satisfiable by craftcms/cms[3.5.0-RC1, 3.5.0-RC1.1, 3.5.0-RC2, 3.5.0-RC3, 3.5.0-RC4, 3.5.0-beta.1, 3.5.0-beta.2, 3.5.0-beta.3, 3.5.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by michaelrog** [comment]
Hmmmm, I may have misunderstood Composer's default behavior. (It seems that if you don't specify a version you want to install, Composer defaults to the latest version, rather than to the latest version that would be compatible with your other requirements.) I'll look into that further.

In the meantime, you can use:

```
composer require topshelfcraft/wordsmith:^3.0
```
