### ISSUE TITLE
Dependency issue causing CI to fail

### ISSUE THREAD

**Issue by thatONEjustin** [TopShelfCraft/Wordsmith#59]
How to reproduce: 

- Install plugin on craft 4.7.1
- run composer install

```shell
Class ParsedownExtraTest located in ./vendor/erusev/parsedown-extra/test/ParsedownExtraTest.php does not comply with psr-0 autoloading standard. Skipping.
```

erusev/parsedown-extra hasn't been updated in 5 years. Should be moved away from.

**Comment by michaelrog** [comment]
Yeah, this has been an annoyance.

I intend to remove Parsedown support (and this dependency) in 5.x. (In fact, given that Craft's native [`markdown` filter](https://craftcms.com/docs/5.x/reference/twig/filters.html#markdown-or-md) supports more flavors, I'll probably remove Markdown parsing from Wordsmith altogether.)

For 4.x — for now, at least — you'll need to suppress that Composer warning, so that your CI can proceed.

(I imagine it may be possible to use a Composer patch to remove or modify this offending test file; I'd welcome a PR for that.)

**Comment by michaelrog** [comment]
Wordsmith `5.0.0` is out now for Craft 5, removing `erusev/parsedown-extra`. ✅
